### ISSUE TITLE
Build envoy in CI for all targets

### ISSUE THREAD

**Issue by lahabana** [kumahq/envoy-builds#3]
### Description

The same artifacts as this: https://github.com/kumahq/envoy-builds/releases/tag/v1.22.1 
But for newer versions of Envoy and built in CI

**Comment by lahabana** [comment]
Some open questions:

- We have alpine vs centos builds. This makes no sense, there should be an underlying reason. There's little difference between [envoy_centos](https://github.com/kumahq/kuma/blob/master/tools/envoy/build_centos.sh#L17) and [envoy_linux](https://github.com/kumahq/kuma/blob/master/tools/envoy/build_linux.sh). What's the real underlying difference? If they are minor can we just have artifacts with these diffs in the name instead of the distribution name?
- Should we build the artifacts in vms we spin and then teardown once we downloaded the built package instead of github runners (makes it simpler for arm, windows, darwin and other esoteric builds)?
- We should add shasums

Pulling inspiration on: https://github.com/425devon/envoy-builds/blob/main/.github/workflows/ci_amd.yaml

What the action could do:

- create release (for schedule from HEAD we start by deleting the last nightly release)
- spin all vms in parallel (A terraform and startup script that actually starts the build could work here)
- The end of the build would likely just upload the artifact to the github release
- teardown all vms

**Comment by michaelbeaumont** [comment]
Resolution of this ticket will be everything in CI but Windows. Windows as automated as possible with clear instructions on how to build and retrieve binary.

**Comment by michaelbeaumont** [comment]
Done
