### ISSUE TITLE
Setting up Darwin machine doesn't work from github action

### ISSUE THREAD

**Issue by lukidzi** [kumahq/envoy-builds#41]
### What happened?

We can notice that when running a job that creates Darwin machine it fails on waiting for instance to be ready. I've tried to create it locally and I can connect to it within 10-12min. We need to investigate if there is something wrong.

**Comment by lahabana** [comment]
@lukidzi is this still the case?

**Comment by michaelbeaumont** [comment]
It looks like this was solved by the above PR
